### ISSUE TITLE
Mt Rainier is not tagged properly

### ISSUE THREAD

**Issue by gumgl** [jgbreault/PinnaclePoints#1]
Not sure if or how you want to fix this → [getClosestExtremalInfo](https://github.com/jgbreault/PinnaclePoints/blob/1d148901621ef1ab0bc4d98cd10b38a88ab91962/scripts/pinnaclePointFormatter.py#L21C21-L21C21). Very cool tool.

![image](https://github.com/jgbreault/PinnaclePoints/assets/4989587/d62f1673-c2f1-476b-820f-a334484fcbee)
![image](https://github.com/jgbreault/PinnaclePoints/assets/4989587/eee8014f-bd11-425b-bfcc-7186fe3781ea)

**Comment by jgbreault** [comment]
In general, I wouldn't trust the names. I got those from Andreas Geyer-Schulz's extremal points (https://nuntius35.gitlab.io/extremal_peaks/) in a somewhat hacky way. If there was an extremal point within 500 m of a pinnacle point, I gave the pinnacle point the same name. The Columbia Crest is part of Mt. Rainer.

Thanks!

**Comment by jgbreault** [comment]
I found a way to improve naming by a lot using PeakBagger data! This pinnacle point is now named Mount Rainier.
